server:
  port: 8080

spring:
  profiles:
    active: ${DB_TYPE:sqlserver}  # Define o perfil ativo, podendo ser 'postgres', 'sqlserver' ou 'oracle'

---
spring:
  config:
    activate:
      on-profile: postgres  # Ativa este bloco quando o perfil é 'postgres'

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/seu_banco}
    username: ${DB_USER:seu_usuario}
    password: ${DB_PASSWORD:sua_senha}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5434/seu_banco}
    user: ${DB_USER:seu_usuario}
    password: ${DB_PASSWORD:sua_senha}
    locations: classpath:db/migration/postgres

---
spring:
  config:
    activate:
      on-profile: sqlserver  # Ativa este bloco quando o perfil é 'sqlserver'

  datasource:
    url: ${DB_URL:jdbc:sqlserver://;serverName=localhost;databaseName=master}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:mySecurePassword123}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:sqlserver://;serverName=localhost;databaseName=master}
    user: ${DB_USER:sa}
    password: ${DB_PASSWORD:mySecurePassword123}
    locations: classpath:db/migration/sqlserver

---
spring:
  config:
    activate:
      on-profile: oracle  # Ativa este bloco quando o perfil é 'oracle'

  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521:ORCL}
    username: ${DB_USER:oracle_user}
    password: ${DB_PASSWORD:oracle_password}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521:ORCL}
    user: ${DB_USER:oracle_user}
    password: ${DB_PASSWORD:oracle_password}
    locations: classpath:db/migration/oracle
