server:
  port: 8080

spring:
  profiles:
    active: ${DB_TYPE:postgres}  # Define o perfil ativo, podendo ser 'postgres' ou 'sqlserver'

---
spring:
  config:
    activate:
      on-profile: postgres  # Ativa este bloco quando o perfil é 'postgres'

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/seu_banco}
    username: ${DB_USER:seu_usuario}
    password: ${DB_PASSWORD:sua_senha}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5434/seu_banco}
    user: ${DB_USER:seu_usuario}
    password: ${DB_PASSWORD:sua_senha}
    locations: classpath:db/migration/postgres

---
spring:
  config:
    activate:
      on-profile: sqlserver  # Ativa este bloco quando o perfil é 'sqlserver'

  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=master}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:YourStrong!Passw0rd}

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=seu_banco_sqlserver}
    user: ${DB_USER:sa}
    password: ${DB_PASSWORD:YourStrong!Passw0rd}
    locations: classpath:db/migration/sqlserver
