
    server:
        port: 8080

    spring:
        datasource:
            url: jdbc:postgresql://localhost:5432/seu_banco
            username: seu_usuario
            password: sua_senha
        jpa:
            hibernate:
            ddl-auto: update
        flyway:
            enabled: true
