server:
  port: 8080

spring:
  profiles:
    active: ${DB_TYPE:sqlserver}  # O perfil padrão é PostgreSQL, mas pode ser alterado via variável de ambiente

---
#spring:
#  config:
#    activate:
#      on-profile: postgres
#  datasource:
#    url: jdbc:postgresql://localhost:5432/seu_banco_postgres
#    username: seu_usuario_postgres
#    password: sua_senha_postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#  flyway:
#    enabled: true
#    url: jdbc:postgresql://localhost:5432/seu_banco_postgres
#    user: seu_usuario_postgres
#    password: sua_senha_postgres
#    locations: classpath:db/migration/postgres  # Localização das migrations do PostgreSQL

---
spring:
  config:
    activate:
      on-profile: sqlserver
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=seu_banco_sqlserver
    username: sa
    password: YourStrong!Passw0rd  # A senha que você definiu no docker-compose.yml
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    url: jdbc:sqlserver://localhost:1433;databaseName=seu_banco_sqlserver
    user: sa
    password: YourStrong!Passw0rd  # A senha que você definiu no docker-compose.yml
    locations: classpath:db/migration/sqlserver  # Localização das migrations do SQL Server
