version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd  # A senha precisa ser complexa e segura
      - MSSQL_PID=Developer  # Pode ser 'Express' para a edição gratuita
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql  # Persistência dos dados

volumes:
  sqlserver_data:
